version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=datadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    image: kdmatrosov/ktor-auth-jwt-frontend 
    ports:
      - 80:8080
    restart: always

volumes:
  pgdata:
